### ISSUE TITLE
Linux SkyrimTogether.exe crash

### ISSUE THREAD

**Issue by FabulousFerret** [tiltedphoques/bug-feature-reports#24]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

## Description

I consistently get this pop up error when trying to launch SkyrimTogether.exe through wine, vortex and mod organizer 2

CoreStubsInit(): Fatal Minhook error.
Error: 127 = Procedure not found.

## Steps to reproduce

1. Launch SkyrimTogether.exe through vortex or wine SkyrimTogether.exe 
2. pop-up appears, launch fails, no extra info in terminal

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [ x ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Launch skyrim together on linux, not picky on what method is used

## Evidence (optional)
![Screenshot from 2022-07-09 21-26-48](https://user-images.githubusercontent.com/70464247/178103659-e279b0b4-3d53-4092-bc91-4d35b14b1315.png)
![Screenshot from 2022-07-09 21-27-32](https://user-images.githubusercontent.com/70464247/178103667-84bee2c2-e012-4ee1-9a94-af7666b9a37f.png)

**Comment by Dragonisser** [comment]
Linux isnt supported.

**Comment by Dragonisser** [comment]
Its more of a feature than a bug.
