### ISSUE TITLE
Healing spells do not work on friendly players

### ISSUE THREAD

**Issue by zhaitan** [tiltedphoques/bug-feature-reports#35]
## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Start the game.
2. Load a saved game where your character is in Whiterun standing inside your house.
3. Connect to the server.
4. Ally takes damage
5. You try to heal them with healing hands
6. No effect

100% reproduction

- [ x ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Friends should be healed but in fact, are not

**Comment by Astral3** [comment]
This issue has already been reported in #2, but we appreciate your report regardless.

**Comment by zhaitan** [comment]
Apologies Astral, I thought I was thorough when I searched the issues but I guess i missed the old report. I'll close it.
