### ISSUE TITLE
Resolution causes shrinkage

### ISSUE THREAD

**Issue by Astral3** [tiltedphoques/bug-feature-reports#4]
## Description

Running the mod above 1440p, such as in 4k, appears to cause a shrinkage effect. A 1440p screen is displayed in the corner, while the rest of the screen that the game should've stretched to is black. This problem _only occurs while ST is running._ [Example](https://cdn.discordapp.com/attachments/995018875664080956/995085876017250435/Screenshot_2022-07-08_17-47-56.png)

## Reproduction rate
- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)

**Comment by Astral3** [comment]
Reportedly, the widescreen fix does not correct this issue.

**Comment by Benubisnitch** [comment]
Figured out the issue. It was dpi scaling for mod organizer causing the game to scale wrong. Still strange the mod caused it to act up.

**Comment by Astral3** [comment]
> Figured out the issue. It was dpi scaling for mod organizer causing the game to scale wrong. Still strange the mod caused it to act up.

Cool, thanks for letting us know!
