### ISSUE TITLE
ESL Reader appears to be broken

### ISSUE THREAD

**Issue by Para0x** [tiltedphoques/bug-feature-reports#51]
_Preamble: I am using mods technically as you've considered Creation Club content to be mods. HOWEVER, the ESL Reader should not be broken. The ESM Creation Club content works without issue._

## Description

If you load any .esl or an ESL flagged .esp they WILL NOT sync in the server. The server does not recognize either plugin type and armors won't sync. Try this on any of the plugins with these flags. Upon removing said flags, the armors work fine.

This implies the ESL Reader is severely broken.

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Start the game with any aforementioned plugin installed
2. Add one of the items within said plugin and equip it.
3. Connect to the server.
4. Look at another user to confirm. (They will show as being in whatever they were wearing previously)
5. Convert the ESPFE or ESL to a ESP by removing the flags from said plugin
6. Repeat to see the assets working again.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

ESL and ESPFE plugins would sync and function correctly.

**Comment by Astral3** [comment]
I have seen numerous mentions of such an issue. Thank you for making a report.

**Comment by RobbeBryssinck** [comment]
The ESL reader is currently not even activated. I'm not sure what you're trying to do here.

**Comment by Para0x** [comment]
> The ESL reader is currently not even activated. I'm not sure what you're trying to do here.

Okay I feel like this should be prefaced somewhere in the wiki? Why was not activated, if I might ask? I thought the ESL Reader might have been bugged or something. My intention was to report a bug of a feature built into the Skyrim SE engine - which is currently missing.

Now I know it's intentionally missing.

**Comment by RobbeBryssinck** [comment]
I'm not entirely sure what you're trying to do here. The ES loader never "synced" mods, whatever that means.

**Comment by Para0x** [comment]
Okay. IF the armor/weapon/equipment appears when the plugin is converted to an ESP, that would [to me] certainly imply the ESL Reader needs to be activated in order for the assets (records which are in the FE index) to be visible on the other player. Currently if it is either an ESL or ESPFE, the assets simply act as if they do not exist on the other player. They do not appear naked - the game simply does not register that they've equipped anything.

**Comment by RobbeBryssinck** [comment]
That's a bug then, but that does not have anything to do with the server side ES loader. Mods don't need the server to sync. If you all have the same load order, then the mods should sync. Regardless, I won't spend too much time on this issue right now, since we don't officially support running Skyrim Together with other mods. Closing this issue.
