### ISSUE TITLE
NPCs only attack host - aggro range and circumstances

### ISSUE THREAD

**Issue by matorina22** [tiltedphoques/bug-feature-reports#52]
No mods installed just normal vanilla special edition with survival enabled on both sides.
NPCs attack only the host or the party leader who is also host...they ignore the second player which is kind of broken...
I don't know how the aggro range works or what are the options for NPC aggro? How are the NPCs choosing their targets depending on certain situations but it seems that currently they only and only focus host which sucks ...
Also death except the gold loss has no meaning.

So please try to fix the NPC aggro and how they prefer their targets.

**Comment by Astral3** [comment]
Hello, this is a duplicate report of #16. Reports need only be made once - if you'd like to contribute further information, please do so as a reply to that thread. 

@RobbeBryssinck Please close as a duplicate.
