### ISSUE TITLE
Golden Saint archer restored to full health

### ISSUE THREAD

**Issue by jibberishmagus** [tiltedphoques/bug-feature-reports#54]
## Description

When in combat with one Golden Saint archer, when one or more players died, one Golden Saint archer's health restored to 100%.

Other Golden Saints died as normal. Group of 5 Golden Saint Daedra with a captive Elytra in a cage, possible story encounter. Wilderness encounter SW of Whiterun.

Related formIDs|
---------------|
Unsure of Golden Saint form - possibly 095E20 (Golden Saint Conjuration) or 1CAD45 (Golden Saint Antronach Forge).

https://en.uesp.net/wiki/Skyrim:Golden_Saint

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"

Enemy health is expected to decrease when damaged, unless sufficient time passes for gradual regeneration.

**Comment by Dragonisser** [comment]
This is a mod. We said we don't support any mods nor AE content.

**Comment by jibberishmagus** [comment]
I installed Skyrim Special Edition directly from Steam without any mods installed that I know of except for Skyrim SE. I didn't know these Golden Saints were from a mod or AE content. I'll go in and see if I have mods I need to turn off, but that's a surprise to me.

**Comment by jibberishmagus** [comment]
Hi, there are four Creation Club mods now packaged in SE. I know you said you don't support mods, but I (and other people) don't know how to turn these off, since they're part of the base installation.

--- details ---

Saints & Seducers: A large mod that rivals a full expansion pack, with multiple quests, armor sets, weapons, and enemies.

Rare Curios: Khajiit caravans get a lot more attractive, with useful items and ingredients imported from around Tamriel.

Survival Mode: Turn Skyim into a survival-crafting adventure as you stay warm and cook meals to stave off exhaustion and hunger.

Fishing: Every RPG needs fishing, and this mod adds over 20 aquatic creatures to catch and cook, display, or drop into an aquarium.

https://pixelkin.org/2021/11/01/four-free-creation-club-mods-coming-to-skyrim-special-edition/

**Comment by Dragonisser** [comment]
> Hi, there are four Creation Club mods now packaged in SE. I know you said you don't support mods, but I (and other people) don't know how to turn these off, since they're part of the base installation.
> 
> --- details ---
> 
> Saints & Seducers: A large mod that rivals a full expansion pack, with multiple quests, armor sets, weapons, and enemies.
> 
> Rare Curios: Khajiit caravans get a lot more attractive, with useful items and ingredients imported from around Tamriel.
> 
> Survival Mode: Turn Skyim into a survival-crafting adventure as you stay warm and cook meals to stave off exhaustion and hunger.
> 
> Fishing: Every RPG needs fishing, and this mod adds over 20 aquatic creatures to catch and cook, display, or drop into an aquarium.
> 
> https://pixelkin.org/2021/11/01/four-free-creation-club-mods-coming-to-skyrim-special-edition/

Simply delete them or move them out of the folder.
