### ISSUE TITLE
Four Creation Club mods now packaged in Skyrim SE w/ base install

### ISSUE THREAD

**Issue by jibberishmagus** [tiltedphoques/bug-feature-reports#56]
## Description

There are four Creation Club mods now packaged in Skyrim SE. I know you said you don't support mods, but I (and other people) don't know how to turn these off, since they're part of the base installation.

This is more an informative bug report, I don't know if a wiki update or footnote is needed on the Reborn page.

## Steps to reproduce

Skyrim Special Edition now comes pre-packaged with four Creation Club Mods (see list below), as part of base install.

Saints & Seducers: A large mod that rivals a full expansion pack, with multiple quests, armor sets, weapons, and enemies.

Rare Curios: Khajiit caravans get a lot more attractive, with useful items and ingredients imported from around Tamriel.

Survival Mode: Turn Skyim into a survival-crafting adventure as you stay warm and cook meals to stave off exhaustion and hunger.

Fishing: Every RPG needs fishing, and this mod adds over 20 aquatic creatures to catch and cook, display, or drop into an aquarium.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"

I know Skyrim Reborn isn't meant to handle mods, so I just want to inform the community that there are four mods pre-packaged with Skyrim SE that don't seem to be uninstallable.

## Evidence (optional)

Show us what happened.

https://pixelkin.org/2021/11/01/four-free-creation-club-mods-coming-to-skyrim-special-edition/

**Comment by RobbeBryssinck** [comment]
These 4 mods are considered fine to run. We don't make any mention of having to disable these. I'll edit the wiki to mention that these can be used, if it is not mentioned there already.
