### ISSUE TITLE
Crashing on connect

### ISSUE THREAD

**Issue by Astral3** [tiltedphoques/bug-feature-reports#7]
## Description

This is a sum thread for everyone experiencing a crash upon connecting to a server.

~~Currently, it is suspected that this problem is due to either user error, inappropriate mod usage, or a PC problem. 
However, due to the influx of such reports with no immediately obvious problem, this issue thread has been created regardless due to possibility of a bug.~~

**This problem appears to occur on some Intel CPUs which do not have AES-NI enabled in the BIOS.**

There are a few (questionable) reports of it occurring on AMD, but most appear to be from intel.

Please specify as much information as possible by following this response guide:

## Mods
If you have mods installed, please attach a list of them. You can use a .txt, pastebin, or hastebin. Do not use any other format.
If you have enginefixes, a camera mod, skyrim souls, or a dll plugin loader installed, your _**report will be ignored**_. 

## Skyrim Version
Please specify what version of Skyrim Special Edition you are using. To do this, open Steam, go to Skyrim SE, _right click on it_, navigate to 'Manage' and then 'Browse local files'.
Right click on SkyrimSE.exe, click Properties, and then Details. _List your File Version here on github in your response._

## Connection Method
Are you all trying to connect via LAN, hamachi, zerotier, radmin, or something else? List it here.

## CPU
Is your CPU an Intel or AMD?

This thread may evolve in the future to seek more information.

**Comment by Endrassel** [comment]
Mods:

Address Library for SKSE Plugins - All in one (Anniversary Edition)

Skyrim Together Reborn

Game Version: 1.6.353.0

Connection Method: Hamachi

**Comment by mikulpro** [comment]
**Details:**    
My friend's game crashes whenever he tries to connect to a valid IP address (of currently running and reachable server) outside of his PC. For invalid addresses it does not crash, only a message that it could not connect appears. If he tries to connect to running localhost server, his game does not crash but the server does. When I try to connect to any other server everything works fine, but when I try to connect to server that this particular friend runs then his server crashes, my game never crashed when we tested it.

We both use vanilla Skyrim Special Edition with Anniversary Edition DLC installed. Sadly my friend refused to uninstall Anniversary Edition DLC thus we did not test it on pure vanilla. But we tried checking file integrity via Steam, reinstalling Skyrim Together Reborn and Address Library. We both tried restarting computers several times.

**Mods:**
Anniversary Edition DLC
Address Library for SKSE Plugins - All in one (Anniversary Edition)
Skyrim Together Reborn

**Game Version:**    1.6.353.0 (both me and my friend)

**Connection Method:**    We have tried all these: Hamachi (VLAN network), Hamachi (HUB-client network), port forwarding on my router (with Hamachi disabled)

**Suggestion:**    I noticed most ppl who have this issue (and have written about it on your Discord server) have Intel processors (my friend as well, I have AMD (Ryzen 7 4800H) and everything works just fine).

Thank You for your time!

**Comment by Endrassel** [comment]
> My friend had this issue. Enabling AES-NI in his bios fixed it.

This might be something. I couldn't host a server either because of an AES issue so had to get my friend to do it.

**Comment by Astral3** [comment]
> My friend had this issue. Enabling AES-NI in his bios fixed it.

I noted your thread earlier, but it appeared to be LAN specific. However, I will take this into account and see if it is the issue. Thanks!

**Comment by Gomiix** [comment]
> My friend had this issue. Enabling AES-NI in his bios fixed it.

Worked for me too. Thanks for the idea, didn't even think about it :). Maybe knowing this helps @Astral3 :)

**Comment by Astral3** [comment]
> > My friend had this issue. Enabling AES-NI in his bios fixed it.
> 
> Worked for me too. Thanks for the idea, didn't even think about it :). Maybe knowing this helps @Astral3 :)

Hi, thank you. The thread has been updated.

**Comment by Joel-56** [comment]
> 

How do I do that though?

> > > My friend had this issue. Enabling AES-NI in his bios fixed it.
> > 
> > 
> > Worked for me too. Thanks for the idea, didn't even think about it :). Maybe knowing this helps @Astral3 :)
> 
> Hi, thank you. The thread has been updated.

How do I do that though?

**Comment by Astral3** [comment]
> > 
> 
> How do I do that though?
> 
> > > > My friend had this issue. Enabling AES-NI in his bios fixed it.
> > > 
> > > 
> > > Worked for me too. Thanks for the idea, didn't even think about it :). Maybe knowing this helps @Astral3 :)
> > 
> > 
> > Hi, thank you. The thread has been updated.
> 
> How do I do that though?

- Go to 'Settings'
- Select 'Update and Security'
- Select 'Recovery'
- Click 'Restart'
- Click 'Troubleshoot'
- Select 'Advanced Options'
- Select 'UEFI Firmware Settings'
---
- You are now within the BIOS. Bios differs depending on Firmware. Search for 'AES', 'AES-NI', 'Data Protection Technology' or 'Advanced Encryption Standard', and Enable it.
- Do not enable anything else. You can /probably/ press F10 to save your settings and exit.

**Comment by Joel-56** [comment]
> 

When my friend looked for AES in their BIOS, nothing showed up, should we just check again?

**Comment by darkjanggo** [comment]
> > > 
> > 
> > 
> > How do I do that though?
> > > > > My friend had this issue. Enabling AES-NI in his bios fixed it.
> > > > 
> > > > 
> > > > Worked for me too. Thanks for the idea, didn't even think about it :). Maybe knowing this helps @Astral3 :)
> > > 
> > > 
> > > Hi, thank you. The thread has been updated.
> > 
> > 
> > How do I do that though?
> 
> * Go to 'Settings'
> * Select 'Update and Security'
> * Select 'Recovery'
> * Click 'Restart'
> * Click 'Troubleshoot'
> * Select 'Advanced Options'
> * Select 'UEFI Firmware Settings'
> 
> * You are now within the BIOS. Bios differs depending on Firmware. Search for 'AES', 'AES-NI', 'Data Protection Technology' or 'Advanced Encryption Standard', and Enable it.
> * Do not enable anything else. You can /probably/ press F10 to save your settings and exit.

I don't have UEFI nor do I have AES or anything like that in the bios

**Comment by Endrassel** [comment]
Yeah doing that worked for me.

**Comment by SpicyStalker** [comment]
I have a server from 2009 without AES support for the cpu (old xeon x3450) is there any way to run this without AES enabled?

**Comment by AleksanderTelecki** [comment]
> 

Same problem :(

**Comment by Astral3** [comment]
As far as I know, no. It seems we simply don't support particularly older CPUs at the moment.

**Comment by ccoser** [comment]
I'm seeing the same thing on an Intel Core i9 (MSI Raider GE76). I can run a server and other computers on my local network can connect, but if I connect to my own server or one run by another system, it just crashes. Unfortunately, my BIOS doesn't have a setting for AES-NI or anything remotely similar so I'm not sure what I can do at this point :'(

**Comment by Astral3** [comment]
> I'm seeing the same thing on an Intel Core i9 (MSI Raider GE76). I can run a server and other computers on my local network can connect, but if I connect to my own server or one run by another system, it just crashes. Unfortunately, my BIOS doesn't have a setting for AES-NI or anything remotely similar so I'm not sure what I can do at this point :'(

Hi, if you're running an I9, your cpu should have a setting for the advanced encryption standards. Which I9 do you have?

**Comment by darkjanggo** [comment]
> So I updated my BIOS and messed around with some other stuff regarding save-games and SOMETHING I did worked. I'm now able to play at last! Thanks to all who replied.

wait wait, what did you do to your saves-games? if that solved your problem and not AES then there may be hope for me after all
